/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Party, Advisor, CategoricalEvent } from "./types";

export const STRANY: Record<string, Party> = {
  ano: {
    id: "ano",
    zkratka: "ANO",
    nazev: "ANO 2011",
    lidr: "Andrej Babiš",
    blok: "vladni",
    preference: 32,
    budget: 1700000,
    popis: "Populistické hnutí. Dominuje předvolebním průzkumům.",
    ekonomika: 35,
    kultura: 25,
    evropa: 25,
    stylPolitiky: 65,
    winPopis: "Vyhraj volby, získej post premiéra a sestav silnou vládu pro naše lidi.",
    barva: "#1a5276",
  },
  motoriste: {
    id: "motoriste",
    zkratka: "MOTO",
    nazev: "Motoristé sobě",
    lidr: "Petr Macinka",
    blok: "vladni",
    preference: 6,
    budget: 400000,
    popis: "Nová pravicová strana motoristů, svobody pohybu a průmyslu.",
    ekonomika: 60,
    kultura: 15,
    evropa: 15,
    stylPolitiky: 80,
    winPopis: "Překroč 5 %, zastav nesmyslné regulace a vybojuj si místo ve vládní koalici.",
    barva: "#c0392b",
  },
  spd: {
    id: "spd",
    zkratka: "SPD",
    nazev: "Svoboda a přímá demokracie",
    lidr: "Tomio Okamura",
    blok: "vladni",
    preference: 9,
    budget: 400000,
    popis: "Nacionalisté. Tvrdá rétorika proti migraci a kritika EU skepticismu.",
    ekonomika: 30,
    kultura: 5,
    evropa: 5,
    stylPolitiky: 95,
    winPopis: "Dostaň se přes 5 % s co nejsilnějším mandátem a prosaď účast SPD ve vládě.",
    barva: "#b03a2e",
  },
  ods: {
    id: "ods",
    zkratka: "ODS",
    nazev: "Občanská demokratická strana",
    lidr: "Martin Kupka",
    blok: "opozicni",
    preference: 14,
    budget: 900000,
    popis: "Tradiční konzervativní pravicová strana s dlouhou parlamentní historií.",
    ekonomika: 75,
    kultura: 35,
    evropa: 45,
    stylPolitiky: 10,
    winPopis: "Obhaj pozici lídra pravice, získej post premiéra a udrž zemi na odpovědné cestě.",
    barva: "#2471a3",
  },
  top09: {
    id: "top09",
    zkratka: "Top09",
    nazev: "TOP 09",
    lidr: "Ondřej Havel",
    blok: "opozicni",
    preference: 6,
    budget: 400000,
    popis: "Liberální pravicová proevropská strana akcentující moderní rozvoj.",
    ekonomika: 75,
    kultura: 60,
    evropa: 85,
    stylPolitiky: 5,
    winPopis: "Překonej 5 % a zajisti stabilní proevropské a rozpočtově odpovědné vládní spojenectví.",
    barva: "#8e44ad",
  },
  kdu: {
    id: "kdu",
    zkratka: "KDU-ČSL",
    nazev: "KDU-ČSL",
    lidr: "Jan Grolich",
    blok: "opozicni",
    preference: 6,
    budget: 350000,
    popis: "Tradiční křesťanskodemokratická strana, hájící regiony a hodnoty rodiny.",
    ekonomika: 50,
    kultura: 25,
    evropa: 75,
    stylPolitiky: 5,
    winPopis: "Mobilizuj regiony, překroč 5 % a buď opět klíčovým jazýčkem na vahách stabilní vlády.",
    barva: "#f1c40f",
  },
  starostove: {
    id: "starostove",
    zkratka: "STAN",
    nazev: "Starostové a nezávislí",
    lidr: "Vít Rakušan",
    blok: "opozicni",
    preference: 8,
    budget: 450000,
    popis: "Středové hnutí zaměřené na regionální rozvoj, decentralizaci a bezpečnost.",
    ekonomika: 60,
    kultura: 70,
    evropa: 85,
    stylPolitiky: 15,
    winPopis: "Dosáhni dvouciferného výsledku a zajisti silné postavení STAN v příští demokratické vládě.",
    barva: "#1abc9c",
  },
  pirati: {
    id: "pirati",
    zkratka: "Piráti",
    nazev: "Česká pirátská strana",
    lidr: "Zdeněk Hřib",
    blok: "opozicni",
    preference: 7,
    budget: 400000,
    popis: "Progresivní strana zaměřená na digitalizaci, transparentnost a mladší voliče.",
    ekonomika: 45,
    kultura: 80,
    evropa: 85,
    stylPolitiky: 40,
    winPopis: "Překroč hranici 5 %, obhaj liberální hodnoty a přines digitalizaci a odvahu do vlády.",
    barva: "#111111",
  },
  kscm: {
    id: "kscm",
    zkratka: "KSČM",
    nazev: "Komunistická strana Čech a Moravy",
    lidr: "Kateřina Konečná",
    blok: "mimo",
    preference: 3,
    budget: 150000,
    popis: "Krajní levice stavějící na odporu vůči NATO, nostalgiích a starších voličích.",
    ekonomika: 10,
    kultura: 20,
    evropa: 10,
    stylPolitiky: 90,
    winPopis: "Prolom 5% hranici, vrať radikální levici do hry a zabojuj o přímý vliv na vládnutí.",
    barva: "#922b21",
  },
  socdem: {
    id: "socdem",
    zkratka: "SocDem",
    nazev: "Sociální demokracie",
    lidr: "Michal Šmarda",
    blok: "mimo",
    preference: 3.5,
    budget: 180000,
    popis: "Tradiční demokratická levicová strana hájící sociální stát a zaměstnance.",
    ekonomika: 30,
    kultura: 50,
    evropa: 65,
    stylPolitiky: 25,
    winPopis: "Obroď tradiční levici, překonej 5 % a vrať sociální spravedlnost přímo do Strakovy akademie.",
    barva: "#e67e22",
  },
  silnecz: {
    id: "silnecz",
    zkratka: "NČ",
    nazev: "Naše Česko",
    lidr: "Martin Kuba",
    blok: "mimo",
    preference: 3,
    budget: 120000,
    popis: "Regionální pragmatické hnutí akcentující průmyslová a regionální specifika.",
    ekonomika: 50,
    kultura: 30,
    evropa: 45,
    stylPolitiky: 50,
    winPopis: "Dokáž, že pragmatická regionální politika funguje, překroč 5 % a staň se členem vlády.",
    barva: "#7f8c8d",
  },
  zeleni: {
    id: "zeleni",
    zkratka: "Zelení",
    nazev: "Strana Zelených",
    lidr: "Gabriela Svárovská",
    blok: "mimo",
    preference: 2.5,
    budget: 120000,
    popis: "Ekologická strana postavená na zelené transformaci, klimatu a právech menšin.",
    ekonomika: 35,
    kultura: 90,
    evropa: 85,
    stylPolitiky: 45,
    winPopis: "Spoj moderní ekologické síly, pokoř 5 % a přines zelenou transformaci přímo do vládního kabinetu.",
    barva: "#27ae60",
  },
};

export const SYMPATIE_INIT: Record<string, Record<string, number | "x">> = {
  ano: { ano: "x", motoriste: 75, spd: 60, ods: 30, top09: 10, kdu: 25, starostove: 10, pirati: 5, kscm: 65, socdem: 75, silnecz: 60, zeleni: 10 },
  motoriste: { ano: 75, motoriste: "x", spd: 55, ods: 35, top09: 30, kdu: 30, starostove: 25, pirati: 10, kscm: 15, socdem: 40, silnecz: 65, zeleni: 0 },
  spd: { ano: 60, motoriste: 55, spd: "x", ods: 5, top09: 5, kdu: 15, starostove: 5, pirati: 0, kscm: 65, socdem: 70, silnecz: 55, zeleni: 5 },
  ods: { ano: 30, motoriste: 35, spd: 5, ods: "x", top09: 85, kdu: 80, starostove: 80, pirati: 60, kscm: 5, socdem: 20, silnecz: 50, zeleni: 55 },
  top09: { ano: 10, motoriste: 30, spd: 5, ods: 85, top09: "x", kdu: 85, starostove: 90, pirati: 75, kscm: 5, socdem: 10, silnecz: 45, zeleni: 65 },
  kdu: { ano: 25, motoriste: 30, spd: 15, ods: 80, top09: 85, kdu: "x", starostove: 80, pirati: 60, kscm: 10, socdem: 20, silnecz: 60, zeleni: 65 },
  starostove: { ano: 10, motoriste: 25, spd: 5, ods: 80, top09: 90, kdu: 80, starostove: "x", pirati: 90, kscm: 5, socdem: 30, silnecz: 55, zeleni: 70 },
  pirati: { ano: 5, motoriste: 10, spd: 0, ods: 60, top09: 75, kdu: 60, starostove: 90, pirati: "x", kscm: 5, socdem: 15, silnecz: 40, zeleni: 95 },
  kscm: { ano: 65, motoriste: 15, spd: 65, ods: 5, top09: 5, kdu: 10, starostove: 5, pirati: 5, kscm: "x", socdem: 95, silnecz: 45, zeleni: 15 },
  socdem: { ano: 75, motoriste: 40, spd: 70, ods: 20, top09: 10, kdu: 20, starostove: 30, pirati: 15, kscm: 95, socdem: "x", silnecz: 55, zeleni: 30 },
  silnecz: { ano: 60, motoriste: 65, spd: 55, ods: 50, top09: 45, kdu: 60, starostove: 55, pirati: 40, kscm: 45, socdem: 55, silnecz: "x", zeleni: 35 },
  zeleni: { ano: 10, motoriste: 0, spd: 5, ods: 55, top09: 65, kdu: 65, starostove: 70, pirati: 95, kscm: 15, socdem: 30, silnecz: 35, zeleni: "x" },
};

export const PORADCI: Record<string, Advisor> = {
  spin_doctor: {
    id: "spin_doctor",
    jmeno: "Marek Prchal",
    emoji: "🎭",
    popis: "Mistr mediální manipulace. Každý skandál otočí ve váš prospěch!",
    specialita: "V mediálních kauzách Vám dodává 50% šanci na dodatečný zisk preferencí!",
    role: "Mediální Mág",
    vahy: { debaty: -5, media: 10, podcast: -5 },
    effects: {
      mediaNegativeImpactMultiplier: 0.5,
      mediaPositiveImpactMultiplier: 1.5,
    },
  },
  klaus: {
    id: "klaus",
    jmeno: "Václav Klaus",
    emoji: "👴",
    popis: "Bývalý prezident. Sice vám toho moc nepřinese, ale vždy sestavíte vládu s motoristy!",
    specialita: "Při finálním vyjednávání máte 100% šanci sestavit vládu s motoristy. Bohužel ale 0% šanci s ODS.",
    role: "Prezidentská Legenda",
    vahy: { debaty: 0, media: 0, podcast: 0 },
    effects: {
      coalitionForcedAccept: ["motoriste"],
      coalitionForcedReject: ["ods"],
    },
  },
  diplomat: {
    id: "diplomat",
    jmeno: "Petr Kolář",
    emoji: "🤝",
    popis: "Zkušený vyjednávač. V pozdních nočních hodinách po sčítání hlasů dokáže vykouzlit i nepravděpodobné koalice!",
    specialita: "Při finálním vyjednávání o koalici vám přidá jednu akci navíc a hlasovací roll se po rollu sníží o dodatečných 10%!",
    role: "Zkušený Diplomat",
    vahy: { debaty: 0, media: 0, podcast: 0 },
    effects: {
      extraDiploActions: 1,
      coalitionRollBonusPct: -10,
    },
  },
  strateg: {
    id: "strateg",
    jmeno: "Miroslav Kalousek",
    emoji: "🗳️",
    popis: "Optimalizuje kampaň podle průzkumů a zkušeností.",
    specialita: "Váha efektu při otázkách z debat je o 50% vyšší!",
    role: "Rozpočtový Strateg",
    vahy: { debaty: 10, media: -5, podcast: -5 },
    effects: {
      debateImpactMultiplier: 1.5,
    },
  },
  populista: {
    id: "populista",
    jmeno: "Jaromír Soukup",
    emoji: "📣",
    popis: "Ví přesně co lidé chtějí slyšet!",
    specialita: "V debatách na CNN a ČT u všech otázek vidí jejich vliv na Hodnotový Kompas. Výkon v debatě pak nemůže být horší než -2% preferencí.",
    role: "Osobnost TV Barrandov",
    vahy: { debaty: -2.5, media: -2.5, podcast: 5 },
    effects: {
      debateImpactClamp: { min: -2, max: 5 },
      podcastChance: 0.35,
    },
  },
  novinar: {
    id: "novinar",
    jmeno: "Radek Bartoníček",
    emoji: "📰",
    popis: "Dokáže ovlivnit své novinářské kolegy, aby o vás lépe psali! Ne však úplně vždy...",
    specialita: "Feedback z podcastů může být pouze pozitivní!",
    role: "Investigativní Novinář",
    vahy: { debaty: -2.5, media: -2.5, podcast: 5 },
    effects: {
      podcastAlwaysPositive: true,
    },
  },
  turek: {
    id: "turek",
    jmeno: "Filip Turek",
    emoji: "🏎️",
    popis: "Počkej, počkej... Vážně přemýšlíš, že by sis vzal(a) Filipa Turka jako svého poradce? Upřímně nedoporučuju, ale zkus to...",
    specialita: "Každou chvíli nová kauza! A co teprve koaliční vyjednávání?",
    role: "Hranatá Legenda",
    vahy: { debaty: -2.5, media: -2.5, podcast: 5 },
    effects: {
      canSendTurek: true,
    },
  },
};

export interface TurekKauza {
  nazev: string;
  popis: string;
}

export const TUREK_KAUZY: TurekKauza[] = [
  { nazev: "Ztracený supersport", popis: "Turek zapomněl, kde zaparkoval své Lamborghini, a omylem ho nahlásil jako ukradené při nájezdu zásahové jednotky na vlastní garáž." },
  { nazev: "Emisní rebelie", popis: "Turek zveřejnil video, kde schválně vypouští dým z veterána přímo na budovu ministerstva životního prostředí, což vyvolalo diplomatickou roztržku." },
  { nazev: "Monoklový skandál", popis: "Turek se pokusil zavést povinné nošení monoklů jakožto „aristokratického doplňku“ v Poslanecké sněmovně, což skončilo rvačkou v bufetu." },
  { nazev: "Syntetické palivo", popis: "Turek propagoval domácí výrobu paliva z použitého fritovacího oleje, což vedlo k masovému ucpání čerpacích stanic v celém kraji." },
  { nazev: "Twitterová ofenzíva", popis: "Turek v návalu emocí označil všechny cyklisty za „agenty chaosu“ a pokusil se navrhnout zákon na jejich zpoplatnění za užívání vzduchu." },
  { nazev: "Audiosystém v plénu", popis: "Turek si do řečnického pultíku tajně nainstaloval subwoofer, aby při každém jeho proslovu podlaha sněmovny vibrovala jako na tuningovém srazu." },
  { nazev: "Ztráta imunity", popis: "Kvůli příliš rychlé jízdě na jednokolce po chodbách parlamentu musel vysvětlovat ústavnímu právníkovi, zda se na něj vztahuje poslanecká imunita." },
  { nazev: "Oblekový protest", popis: "Turek odmítl vystoupit v televizi, protože vizážistka chtěla, aby si sundal manžetové knoflíčky, které považuje za svou „politickou identitu“." },
  { nazev: "Tuning legislativy", popis: "Turek se pokusil protlačit pozměňovací návrh, který by legálně umožňoval instalaci neonových podsvícení na sanitky pro „lepší viditelnost v noci“." },
  { nazev: "Retro-digitalizace", popis: "Turek navrhl, aby se veškerá státní správa vrátila k psacím strojům, protože digitální data jsou podle něj „příliš náchylná na vliv mimozemšťanů“." },
  { nazev: "Velká cena sněmovny", popis: "Turek zorganizoval ilegální závod kancelářských židlí na chodbách, který skončil destrukcí historického portrétu jednoho z ministrů." },
  { nazev: "Parfémovaná politika", popis: "Turek uvedl na trh vlastní vůni „Benzín a moc“, která však podle hygienické stanice obsahovala stopy vysoce hořlavých látek." },
  { nazev: "Sběratelská krize", popis: "V rámci šetření majetkových přiznání se zjistilo, že Turekova sbírka veteránů má větší hodnotu než státní rozpočet na kulturu." },
  { nazev: "Tuningová interpelace", popis: "Turek interpeloval premiéra ohledně kvality asfaltu na dálnici D1, protože si při cestě na jednání poškrábal přední spojler." },
  { nazev: "Analytický omyl", popis: "Turek citoval neexistující studii o tom, že spalovací motory ve skutečnosti čistí vzduch, což vedlo k mezinárodní vědecké debatě." },
  { nazev: "Čajový dýchánek", popis: "Turek se pokusil v parlamentu zavést „hodinu gentlemanů“ s doutníky, což vedlo k okamžitému spuštění protipožárního systému." },
  { nazev: "Algoritmický boj", popis: "Turek obvinil Google z „politické diskriminace“, protože jeho jméno v našeptávači po napsání slova „kontroverzní“ vyskočilo jako první." },
  { nazev: "Ztracený projev", popis: "Turek zapomněl si připravit projev, tak začal z paměti přednášet technickou příručku k motoru V12, což parlament poslouchal v naprostém úžasu." },
  { nazev: "Kravatová diplomacie", popis: "Turek vyvolal krizi v koalici, když se odmítl zúčastnit oficiální večeře, protože hostitelé podávají víno ve sklenicích, které se mu „nehodily ke kravatě“." },
  { nazev: "Generační střet", popis: "Turek založil „Hnutí za práva řidičů ročníku 1990 a starších“, které má za cíl zakázat moderní asistenty v autech jako „přílišné změkčování“." }
];
